spring:
  application:
    name: osiv-example

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: admin
  jpa:
    show-sql: true
    open-in-view: false

logging:
  level:
    org.example.osivdemo: debug
